WINDOW_TITLE="The Maze Builder"
#Less than 50 will need to increase recursion, if commented out in main
CELL_SIZE=50
LINE_THICK=4
WINDOW_SIZE_X=1200
WINDOW_SIZE_Y=800
NORMAL_WIN_X = WINDOW_SIZE_X//CELL_SIZE * CELL_SIZE
NORMAL_WIN_Y = WINDOW_SIZE_Y//CELL_SIZE * CELL_SIZE
MAZE_DRAW_SPEED=0.0
LINE_DRAW_SPEED=0.05
UNDO_LINE_SPEED=0.1
